spring:
  config:
    import:
      - optional:configserver:http://ms-configserver:8888
  application:
    name: query-balance-service
server:
  port: 8086
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-balance: /api/v1/balance